# Generated by Django 5.0 on 2024-02-06 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_remove_allservicequality_count_surveys_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allservicequality",
            name="updated_at",
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="allsustainability",
            name="updated_at",
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="indicator",
            name="updated_at",
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="sentimentanalysis",
            name="updated_at",
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="servicequality",
            name="updated_at",
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="sustainability",
            name="updated_at",
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
