version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - media_volume:/usr/src/resetlytics/media
  web:
    build: ./resetlytics
    command: gunicorn resetlytics.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./resetlytics/:/usr/src/resetlytics/
      - media_volume:/usr/src/resetlytics/media
    expose:
      - 8000
    env_file:
      - ./resetlytics/.env.prod
    depends_on:
      - db
  db:
    image: mysql:8.2
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./database/.env.prod.db

volumes:
  mysql_data:
  media_volume:
