version: '3.8'

services:
  web:
    build: ./resetlytics
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./resetlytics/:/usr/src/resetlytics/
    expose:
      - 8000
    env_file:
      - ./resetlytics/.env.dev
    depends_on:
      - db
  db:
    image: mysql:8.2
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql 
      - mysql_logs:/var/log/mysql
    env_file:
      - ./database/.env.prod.db

volumes:
  mysql_data:
