
services:

  # Database
  # data must be persisted
  database:
    container_name: resetlytics_database
    build: ./database
    restart: always #unless-stopped
    #ports:
    #  - "3306:3306"  should get by default - see .env.prod. in the backend
    env_file:
      - ./database/.env.prod.db
    volumes:
      # for persistence
      - mysql-data:/var/lib/mysql 
      - mysql-logs:/var/log/mysql


  # Backend (Django with Gunicorn server)
  backend:
    container_name: resetlytics_backend
    build: ./backend
    command: sleep infinity
    # storage volumes
    # volumes:
    #   - static_volume: ...../staticfiles
    #   - media_volume: .../media
    expose:
      - 8000
    ports:
      - "8000:8000"
    env_file:
      - ./backend/resetlytics/.env.prod
    depends_on:
      - database
  
  # Frontend (Next.js)
  frontend:
    container_name: resetlytics_frontend
    build: ./frontend
    ports: 
      - "3000:3000"
    depends_on:
      - backend

  # Nginx Reverse Proxy with TLS
  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
      - "443:443" # check this one
    volumes:
      # has to be updated (avoids Dockerfile)
      - ./nginx.conf:/etc/nginx/nginx.conf 
      # make sure to put cert and key in ./ssl
      - ./ssl/:/etc/nginx/ssl/
      #- media_volume:/home/backend/mediafiles
    depends_on:
      - backend
      - frontend
    
# Define named volumes for persistence
volumes:
  mysql-data:
  mysql-logs:
