# Use an official MySQL runtime as a parent image
FROM mysql:8.2

# Set the working directory in the container
WORKDIR /database

# Expose the port 
EXPOSE 3306

# Copy local files into the image 
COPY . .

