# Generated by Django 5.0 on 2024-01-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_organization_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allservicequality",
            name="count_surveys",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="allsustainability",
            name="count_surveys",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="questionblock",
            name="count_questions",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
