# Generated by Django 5.0 on 2024-01-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_questionblock_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="question_number",
            new_name="number",
        ),
        migrations.AddField(
            model_name="questionblock",
            name="options",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
