# Generated by Django 5.0 on 2024-01-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_question_text_translations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionblock",
            name="options",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="questionblock",
            name="scale",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
