# Generated by Django 5.0 on 2024-02-06 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_rename_ip_address_respondent_digital_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="respondent",
            name="survey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respondents",
                to="app.survey",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="organizations",
            field=models.ManyToManyField(to="app.organization"),
        ),
    ]
