# Generated by Django 5.0 on 2024-02-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_allservicequality_demographics_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="year",
            field=models.PositiveIntegerField(default=2023),
        ),
    ]
