# Generated by Django 5.0 on 2024-02-10 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_indicator_year"),
    ]

    operations = [
        migrations.RenameField(
            model_name="indicator",
            old_name="updated_at",
            new_name="Q1_updated_at",
        ),
        migrations.AddField(
            model_name="indicator",
            name="Q2_updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="indicator",
            name="Q3_updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="indicator",
            name="Q4_updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="indicator",
            name="previous_year_updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="indicator",
            name="scale_max",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="indicator",
            name="scale_min",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="indicator",
            name="year_to_date_updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="year",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
