# Generated by Django 5.0 on 2024-01-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_allservicequality_count_surveys_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionblock",
            name="number",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
