# Generated by Django 5.0 on 2024-01-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_question_text_translations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="text_translations",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="questionblock",
            name="options",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="questionblock",
            name="scale",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="questionblock",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="questionblock",
            name="title_translations",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="introduction",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="introduction_translations",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="title_translations",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="survey",
            name="introduction",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="survey",
            name="introduction_translations",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="survey",
            name="title_translations",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
