# Generated by Django 5.0 on 2024-01-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_questionblock_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionblock",
            name="options",
            field=models.TextField(blank=True, null=True),
        ),
    ]
