# Generated by Django 5.0 on 2024-01-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_questionblock_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="access_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="respondent",
            name="access_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="questionblock",
            name="category",
            field=models.CharField(
                choices=[
                    ("Categorical", "Categorical"),
                    ("Categorical-many", "Categorical Many"),
                    ("Ordinal", "Ordinal"),
                    ("Ordinal-many", "Ordinal Many"),
                    ("Commentary", "Commentary"),
                ],
                default="Ordinal",
                max_length=50,
            ),
        ),
    ]
