# Generated by Django 5.0 on 2024-02-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_answer_access_url_answer_score_respondent_access_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="purpose",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
