# Generated by Django 5.0 on 2024-02-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_questionnaire_purpose"),
    ]

    operations = [
        migrations.RenameField(
            model_name="respondent",
            old_name="IP_address",
            new_name="digital_ID",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="access_url",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="option_order",
        ),
        migrations.AddField(
            model_name="answer",
            name="selection",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="answer",
            name="score",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="answer",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="questionblock",
            name="criterion",
            field=models.CharField(
                choices=[
                    ("Service", "Service"),
                    ("Environment", "Environment"),
                    ("Reservation", "Reservation"),
                    ("Technology", "Technology"),
                    ("Staff", "Staff"),
                    ("Sustainability", "Sustainability"),
                    ("Satisfaction", "Satisfaction"),
                    ("Demographics", "Demographics"),
                    ("General", "General"),
                ],
                default="General",
                max_length=50,
            ),
        ),
    ]
